# Generated by Django 4.1.2 on 2023-11-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8, verbose_name='Name')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Pumps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8, verbose_name='Name')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Клапан',
                'verbose_name_plural': 'Клапана',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='PumpStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pumps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumpsapp.pumps')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumpsapp.status')),
            ],
            options={
                'verbose_name': 'Статус насоса',
                'verbose_name_plural': 'Статусы насосов',
            },
        ),
        migrations.CreateModel(
            name='GroupsPumps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumpsapp.groups')),
            ],
            options={
                'verbose_name': 'Группа клапана',
                'verbose_name_plural': 'Группы клапан',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='pumps',
            field=models.ManyToManyField(to='pumpsapp.pumps'),
        ),
    ]
