# Generated by Django 4.1.2 on 2023-11-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='pumps',
        ),
        migrations.AddField(
            model_name='groupspumps',
            name='pumps',
            field=models.ManyToManyField(to='pumpsapp.pumps'),
        ),
    ]
