# Generated by Django 4.1.2 on 2023-12-02 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pumpsapp', '0002_remove_groups_pumps_groupspumps_pumps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupspumps',
            name='pumps',
        ),
        migrations.AddField(
            model_name='groupspumps',
            name='pumps',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pumpsapp.pumps'),
            preserve_default=False,
        ),
    ]
