# Generated by Django 4.1.2 on 2023-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpsapp', '0003_remove_groupspumps_pumps_groupspumps_pumps'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
